name: Guard Docs on Main

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            docs/**/*.md

      - name: Run guard check for each changed file
        id: guard-check
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          EUTELO_GUARD_API_ENDPOINT: ${{ secrets.EUTELO_GUARD_API_ENDPOINT }}
          EUTELO_GUARD_API_KEY: ${{ secrets.EUTELO_GUARD_API_KEY }}
          EUTELO_GUARD_MODEL: ${{ secrets.EUTELO_GUARD_MODEL }}
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
          
          # Process each changed file
          for file in $CHANGED_FILES; do
            if [ ! -f "$file" ]; then
              echo "Skipping deleted file: $file"
              continue
            fi
            
            echo "Checking: $file"
            
            # Run guard for this file (guard will automatically collect related documents)
            # Use --depth=1 to limit traversal depth for CI performance
            npx eutelo guard --depth=1 "$file" || GUARD_EXIT=$?
          done
          
          # Exit with error if any guard check failed
          exit ${GUARD_EXIT:-0}
