name: Guard Docs Manually

on:
  workflow_dispatch:
    inputs:
      paths:
        description: 'Space-separated paths to evaluate'
        default: 'docs/**/*.md'
      working-directory:
        description: 'Optional subdirectory (e.g. apps/web)'
        default: '.'
      format:
        description: 'Switch to json when you need structured output'
        default: 'text'
      depth:
        description: 'Depth for related document traversal (default: 1)'
        default: '1'

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ inputs.working-directory }}

      - name: Build packages
        run: npm run build
        working-directory: ${{ inputs.working-directory }}

      - name: Run guard check
        working-directory: ${{ inputs.working-directory }}
        env:
          EUTELO_GUARD_API_ENDPOINT: ${{ secrets.EUTELO_GUARD_API_ENDPOINT }}
          EUTELO_GUARD_API_KEY: ${{ secrets.EUTELO_GUARD_API_KEY }}
          EUTELO_GUARD_MODEL: ${{ secrets.EUTELO_GUARD_MODEL }}
        run: |
          INPUT_PATHS="${{ inputs.paths }}"
          OUTPUT_FORMAT="${{ inputs.format }}"
          DEPTH="${{ inputs.depth }}"
          
          FORMAT_FLAG=""
          if [ "$OUTPUT_FORMAT" = "json" ]; then
            FORMAT_FLAG="--format json"
          fi
          
          DEPTH_FLAG=""
          if [ -n "$DEPTH" ] && [ "$DEPTH" != "1" ]; then
            DEPTH_FLAG="--depth $DEPTH"
          fi
          
          # Expand glob patterns and get actual files
          for pattern in $INPUT_PATHS; do
            for file in $pattern; do
              if [ -f "$file" ]; then
                echo "Checking: $file"
                # Run guard for this file (guard will automatically collect related documents)
                npx eutelo align $FORMAT_FLAG $DEPTH_FLAG "$file" || GUARD_EXIT=$?
              fi
            done
          done
          
          exit ${GUARD_EXIT:-0}
